### ISSUE TITLE
Code of conduct implementation?

### ISSUE THREAD

**Issue by xunga** [lisk-builders/lisk-builders#33]
Hey Builders,

I was wondering if it would be possible to create a code of conduct/house rules in order to partecipate to our community. What do you think about this idea?

**Comment by alepop** [comment]
@xunga good idea. Will you make a pr?

**Comment by xunga** [comment]
@alepop All righty! I'll make a PR with a proposal :)

**Comment by xunga** [comment]
Issue solved with PR #56
